import fs from "node:fs";

const path = "C:/Users/juanc/Documents/Codex/2026-06-10/create-me-a-direct-step-by/app.js";
let text = fs.readFileSync(path, "latin1");

function replaceExact(oldText, newText, label) {
  if (!text.includes(oldText)) throw new Error(`Missing block: ${label}`);
  text = text.replace(oldText, newText);
}

function replaceRegex(pattern, replacement, label) {
  if (!pattern.test(text)) throw new Error(`Missing pattern: ${label}`);
  text = text.replace(pattern, replacement);
}

replaceExact(
  [
    "async function loadBuyData() {",
    "  if (window.BUY_ITEMS_DATA) return window.BUY_ITEMS_DATA;",
    "  try {",
    "    const response = await fetch(\"./buy_items_data.js?v=20260614f\", { cache: \"no-store\" });",
    "    if (response.ok) {",
    "      const text = await response.text();",
    "      new Function(text)();",
    "      if (window.BUY_ITEMS_DATA) return window.BUY_ITEMS_DATA;",
    "    }",
    "  } catch (error) {",
    "    console.warn(\"Buy items data fallback failed\", error);",
    "  }",
    "  return { items: [], ships: [], rentals: [] };",
    "}",
    "",
  ].join("\n"),
  [
    "async function loadBuyData() {",
    "  const baseData = window.BUY_ITEMS_DATA || { items: [], ships: [], rentals: [] };",
    "  const partsData = window.BUY_ITEMS_DATA_PARTS || {};",
    "",
    "  const normalizeKey = (entry) => String(entry?.id || entry?.name || \"\").trim().toLowerCase();",
    "  const mergeRecord = (primary = {}, secondary = {}) => {",
    "    const merged = { ...primary, ...secondary };",
    "    merged.offers = Array.isArray(secondary.offers) && secondary.offers.length ? secondary.offers : Array.isArray(primary.offers) ? primary.offers : [];",
    "    merged.loadoutCategories = Array.isArray(secondary.loadoutCategories) && secondary.loadoutCategories.length ? secondary.loadoutCategories : Array.isArray(primary.loadoutCategories) ? primary.loadoutCategories : [];",
    "    merged.loadoutWeapons = Array.isArray(secondary.loadoutWeapons) && secondary.loadoutWeapons.length ? secondary.loadoutWeapons : Array.isArray(primary.loadoutWeapons) ? primary.loadoutWeapons : [];",
    "    merged.loadoutComponents = Array.isArray(secondary.loadoutComponents) && secondary.loadoutComponents.length ? secondary.loadoutComponents : Array.isArray(primary.loadoutComponents) ? primary.loadoutComponents : [];",
    "    merged.prices = secondary.prices || primary.prices || merged.prices || {};",
    "    return merged;",
    "  };",
    "  const mergeByKey = (primary = [], secondary = [], keyFn = normalizeKey) => {",
    "    const map = new Map();",
    "    for (const entry of Array.isArray(primary) ? primary : []) {",
    "      const key = keyFn(entry);",
    "      if (key) map.set(key, entry);",
    "    }",
    "    for (const entry of Array.isArray(secondary) ? secondary : []) {",
    "      const key = keyFn(entry);",
    "      if (!key) continue;",
    "      map.set(key, mergeRecord(map.get(key) || {}, entry));",
    "    }",
    "    return [...map.values()];",
    "  };",
    "",
    "  const items = mergeByKey(baseData.items || [], partsData.items?.items || []);",
    "  const ships = mergeByKey(baseData.ships || [], partsData.ships?.ships || []);",
    "  const shipByName = new Map(ships.map((entry) => [String(entry?.name || \"\").trim().toLowerCase(), entry]));",
    "  const rentalsMerged = mergeByKey(baseData.rentals || [], partsData.rentals?.rentals || []);",
    "  const rentals = rentalsMerged.map((entry) => {",
    "    const ship = shipByName.get(String(entry?.name || \"\").trim().toLowerCase());",
    "    if (!ship) return entry;",
    "    return mergeRecord(ship, entry);",
    "  });",
    "  return { items, ships, rentals };",
    "}",
    "",
  ].join("\n"),
  "loadBuyData"
);

replaceRegex(
  /function buyEntryShipCareer\(entry\) \{[\s\S]*?\nfunction buySearchText\(entry, tab = state\.buyTab\) \{/,
  [
    "function buyEntryShipCareer(entry) {",
    "  return normalizeText(entry?.career || entry?.careerRole || entry?.careerType || \"\");",
    "}",
    "",
    "function buyEntryShipRole(entry) {",
    "  return normalizeText(entry?.role || entry?.shipRole || entry?.roleType || \"\");",
    "}",
    "",
    "function buyEntryShipSize(entry) {",
    "  const text = String(entry?.size || \"\").trim();",
    "  const match = text.match(/^(Small|Medium|Large|Capital|Snub)\\b/i);",
    "  return match ? match[1][0].toUpperCase() + match[1].slice(1).toLowerCase() : \"\";",
    "}",
    "",
    "function splitOfferLocation(location) {",
    "  return normalizeText(location)",
    "    .split(/\\s*-\\s*/)",
    "    .map((part) => part.trim())",
    "    .filter(Boolean);",
    "}",
    "",
    "const BUY_KNOWN_SYSTEMS = new Set([\"Nyx\", \"Pyro\", \"Stanton\"]);",
    "",
    "function firstSystemSegment(parts) {",
    "  for (const part of parts) {",
    "    const segment = normalizeText(part).split(/\\s*>\\s*/)[0]?.trim();",
    "    if (BUY_KNOWN_SYSTEMS.has(segment)) return segment;",
    "  }",
    "  return \"\";",
    "}",
    "",
    "function offerSystem(offer) {",
    "  const explicit = normalizeText(offer?.system);",
    "  const explicitPrimary = explicit.split(/\\s*>\\s*/)[0]?.trim();",
    "  if (BUY_KNOWN_SYSTEMS.has(explicitPrimary)) return explicitPrimary;",
    "  const derived = firstSystemSegment(splitOfferLocation(offer?.locationLabel || offer?.locationPath || offer?.location));",
    "  return derived || \"Other\";",
    "}",
    "",
    "function offerArea(offer) {",
    "  const explicit = normalizeText(offer?.area);",
    "  const rawLocation = normalizeText(offer?.locationLabel || offer?.locationPath || offer?.location);",
    "  const badExplicit =",
    "    !explicit ||",
    "    explicit === \"Other\" ||",
    "    explicit === rawLocation ||",
    "    explicit.includes(\" - \") ||",
    "    BUY_KNOWN_SYSTEMS.has(explicit);",
    "  if (!badExplicit) return explicit;",
    "  const parts = splitOfferLocation(rawLocation);",
    "  if (!parts.length) return explicit || \"Other\";",
    "  if (BUY_KNOWN_SYSTEMS.has(parts[0])) {",
    "    return parts[1] || parts[parts.length - 1] || explicit || \"Other\";",
    "  }",
    "  return parts[1] || parts[parts.length - 1] || explicit || \"Other\";",
    "}",
    "",
    "function offerLocationName(offer) {",
    "  const labelParts = splitOfferLocation(offer?.locationLabel);",
    "  if (labelParts.length) return labelParts[0];",
    "  const pathParts = splitOfferLocation(offer?.locationPath);",
    "  if (pathParts.length) return pathParts[pathParts.length - 1];",
    "  const parts = splitOfferLocation(offer?.location);",
    "  if (!parts.length) return normalizeText(offer?.locationName || \"Unknown location\");",
    "  const system = offerSystem(offer);",
    "  if (BUY_KNOWN_SYSTEMS.has(parts[0]) || system !== \"Other\") {",
    "    return parts[parts.length - 1] || parts[0];",
    "  }",
    "  return parts[0];",
    "}",
    "",
    "function buyOfferMatches(offer, system, area, location) {",
    "  if (!offer) return false;",
    "  if (system !== \"All\" && offerSystem(offer) !== system) return false;",
    "  if (area !== \"All\" && offerArea(offer) !== area) return false;",
    "  if (location !== \"All\" && offerLocationName(offer) !== location) return false;",
    "  return true;",
    "}",
    "",
    "function filteredBuyOffers(entry, system = state.buySystem, area = state.buyArea, location = state.buyLocation) {",
    "  return buyEntryOffers(entry).filter((offer) => buyOfferMatches(offer, system, area, location));",
    "}",
    "",
    "function buySystems() {",
    "  return [\"All\", \"Nyx\", \"Pyro\", \"Stanton\"];",
    "}",
    "",
    "function buyAreas(system = state.buySystem) {",
    "  const areas = new Set();",
    "  for (const entry of buyEntriesForTab()) {",
    "    for (const offer of buyEntryOffers(entry)) {",
    "      if (system !== \"All\" && offerSystem(offer) !== system) continue;",
    "      areas.add(offerArea(offer));",
    "    }",
    "  }",
    "  return [\"All\", ...[...areas].sort((a, b) => a.localeCompare(b, undefined, { sensitivity: \"base\" }))];",
    "}",
    "",
    "function buyLocations(system = state.buySystem, area = state.buyArea) {",
    "  const locations = new Set();",
    "  for (const entry of buyEntriesForTab()) {",
    "    for (const offer of buyEntryOffers(entry)) {",
    "      if (system !== \"All\" && offerSystem(offer) !== system) continue;",
    "      if (area !== \"All\" && offerArea(offer) !== area) continue;",
    "      locations.add(offerLocationName(offer));",
    "    }",
    "  }",
    "  return [\"All\", ...[...locations].sort((a, b) => a.localeCompare(b, undefined, { sensitivity: \"base\" }))];",
    "}",
    "",
    "function buyTypeOptions() {",
    "  const types = new Set();",
    "  for (const entry of buyEntriesForTab()) {",
    "    const value = buyEntryType(entry);",
    "    if (!isBadLabel(value)) types.add(value);",
    "  }",
    "  return [\"All\", ...[...types].sort((a, b) => a.localeCompare(b, undefined, { sensitivity: \"base\" }))];",
    "}",
    "",
    "function buySubtypeOptions() {",
    "  const subtypes = new Set();",
    "  for (const entry of buyEntriesForTab()) {",
    "    if (state.buyType !== \"All\" && buyEntryType(entry) !== state.buyType) continue;",
    "    const value = buyEntrySubtype(entry);",
    "    if (!isBadLabel(value)) subtypes.add(value);",
    "  }",
    "  return [\"All\", ...[...subtypes].sort((a, b) => a.localeCompare(b, undefined, { sensitivity: \"base\" }))];",
    "}",
    "",
    "function buySizeOptions() {",
    "  const sizes = new Set();",
    "  for (const entry of buyEntriesForTab()) {",
    "    if (state.buyType !== \"All\" && buyEntryType(entry) !== state.buyType) continue;",
    "    if (state.buySubtype !== \"All\" && buyEntrySubtype(entry) !== state.buySubtype) continue;",
    "    const value = buyEntrySize(entry);",
    "    if (!isBadLabel(value)) sizes.add(value);",
    "  }",
    "  return [\"All\", ...[...sizes].sort((a, b) => a.localeCompare(b, undefined, { sensitivity: \"base\" }))];",
    "}",
    "",
    "function shipFilterOptions(mapper) {",
    "  const values = new Set();",
    "  for (const entry of buyEntriesForTab(\"ships\")) {",
    "    const value = mapper(entry);",
    "    if (Array.isArray(value)) {",
    "      for (const item of value) {",
    "        if (!isBadLabel(item)) values.add(item);",
    "      }",
    "      continue;",
    "    }",
    "    if (!isBadLabel(value)) values.add(value);",
    "  }",
    "  return [\"All\", ...[...values].sort((a, b) => a.localeCompare(b, undefined, { sensitivity: \"base\" }))];",
    "}",
    "",
    "function buyShipCareerOptions() {",
    "  return shipFilterOptions((entry) => buyEntryShipCareer(entry));",
    "}",
    "",
    "function buyShipRoleOptions() {",
    "  return shipFilterOptions((entry) => buyEntryShipRole(entry));",
    "}",
    "",
    "function buyShipSizeOptions() {",
    "  return shipFilterOptions((entry) => buyEntryShipSize(entry));",
    "}",
    "",
    "function buyShipWeaponOptions() {",
    "  return shipFilterOptions((entry) => entry?.loadoutWeapons || []);",
    "}",
    "",
    "function buyShipComponentOptions() {",
    "  return shipFilterOptions((entry) => entry?.loadoutComponents || []);",
    "}",
    "",
    "function buySearchText(entry, tab = state.buyTab) {",
  ].join("\n") + "\n",
  "buy helper block"
);

replaceRegex(
  /function filteredBuyEntries\(\) \{[\s\S]*?\nfunction currentBuyEntry\(\) \{/,
  [
    "function filteredBuyEntries() {",
    "  const query = norm(state.buySearch);",
    "  return buyEntriesForTab()",
    "    .filter((entry) => {",
    "      if (state.buyType !== \"All\" && buyEntryType(entry) !== state.buyType) return false;",
    "      if (state.buySubtype !== \"All\" && buyEntrySubtype(entry) !== state.buySubtype) return false;",
    "      if (state.buyTab !== \"items\" && state.buyShipCareer !== \"All\" && buyEntryShipCareer(entry) !== state.buyShipCareer) return false;",
    "      if (state.buyTab !== \"items\" && state.buyShipSize !== \"All\" && buyEntrySize(entry) !== state.buyShipSize) return false;",
    "      if (state.buyTab !== \"items\" && state.buyShipRole !== \"All\" && buyEntryShipRole(entry) !== state.buyShipRole) return false;",
    "      if (state.buyTab !== \"items\" && state.buyShipWeapon !== \"All\") {",
    "        const weapons = Array.isArray(entry?.loadoutWeapons) ? entry.loadoutWeapons : [];",
    "        if (!weapons.includes(state.buyShipWeapon)) return false;",
    "      }",
    "      if (state.buyTab !== \"items\" && state.buyShipComponent !== \"All\") {",
    "        const components = Array.isArray(entry?.loadoutComponents) ? entry.loadoutComponents : [];",
    "        if (!components.includes(state.buyShipComponent)) return false;",
    "      }",
    "      const offers = buyEntryOffers(entry);",
    "      if (offers.length) {",
    "        if (!offers.some((offer) => buyOfferMatches(offer, state.buySystem, state.buyArea, state.buyLocation))) return false;",
    "      } else if (state.buySystem !== \"All\" || state.buyArea !== \"All\" || state.buyLocation !== \"All\") {",
    "        return false;",
    "      }",
    "      if (!query) return true;",
    "      return buyEntryName(entry).toLowerCase().includes(query);",
    "    })",
    "    .sort((a, b) => buyEntryName(a).localeCompare(buyEntryName(b), undefined, { sensitivity: \"base\" }));",
    "}",
    "",
    "function currentBuyEntry() {",
  ].join("\n") + "\n",
  "filtered buy entries"
);

replaceRegex(
  /function selectBuyTab\(tab\) \{[\s\S]*?\nfunction selectBuyEntry\(entry\) \{/,
  [
    "function selectBuyTab(tab) {",
    "  state.buyTab = tab || \"items\";",
    "  state.buySelectedId = \"\";",
    "  state.buyType = \"All\";",
    "  state.buySubtype = \"All\";",
    "  state.buyShipCareer = \"All\";",
    "  state.buyShipSize = \"All\";",
    "  state.buyShipRole = \"All\";",
    "  state.buyShipWeapon = \"All\";",
    "  state.buyShipComponent = \"All\";",
    "  state.buySystem = \"All\";",
    "  state.buyArea = \"All\";",
    "  state.buyLocation = \"All\";",
    "  renderAll();",
    "}",
    "",
    "function selectBuyEntry(entry) {",
  ].join("\n") + "\n",
  "select buy tab"
);

replaceRegex(
  /function buyLocationSummary\(entry\) \{[\s\S]*?\nfunction renderBuy\(\) \{/,
  [
    "function buyLocationSummary(entry) {",
    "  const offers = filteredBuyOffers(entry);",
    "  if (!offers.length) return \"No locations\";",
    "  const first = offerLocationName(offers[0]);",
    "  return offers.length === 1 ? first : `${first} + ${formatCount(offers.length - 1)} more`;",
    "}",
    "",
    "function renderBuy() {",
  ].join("\n"),
  "buy location summary"
);

replaceRegex(
  /const sizes = buySizeOptions\(\);\n  if \(state\.buyTab === "ships" && !sizes\.includes\(state\.buyShipSize\)\) state\.buyShipSize = "All";\n  const shipRoles = buyShipRoleOptions\(\);\n  if \(state\.buyTab === "ships" && !shipRoles\.includes\(state\.buyShipRole\)\) state\.buyShipRole = "All";\n  const shipWeaponOptions = buyShipWeaponOptions\(\);\n  if \(state\.buyTab === "ships" && !shipWeaponOptions\.includes\(state\.buyShipWeapon\)\) state\.buyShipWeapon = "All";\n  const shipComponentOptions = buyShipComponentOptions\(\);\n  if \(state\.buyTab === "ships" && !shipComponentOptions\.includes\(state\.buyShipComponent\)\) state\.buyShipComponent = "All";/,
  [
    "const shipCareerOptions = buyShipCareerOptions();",
    "  if (state.buyTab !== \"items\" && !shipCareerOptions.includes(state.buyShipCareer)) state.buyShipCareer = \"All\";",
    "  const shipRoles = buyShipRoleOptions();",
    "  if (state.buyTab !== \"items\" && !shipRoles.includes(state.buyShipRole)) state.buyShipRole = \"All\";",
    "  const shipSizes = buyShipSizeOptions();",
    "  if (state.buyTab !== \"items\" && !shipSizes.includes(state.buyShipSize)) state.buyShipSize = \"All\";",
    "  const shipWeaponOptions = buyShipWeaponOptions();",
    "  if (state.buyTab !== \"items\" && !shipWeaponOptions.includes(state.buyShipWeapon)) state.buyShipWeapon = \"All\";",
    "  const shipComponentOptions = buyShipComponentOptions();",
    "  if (state.buyTab !== \"items\" && !shipComponentOptions.includes(state.buyShipComponent)) state.buyShipComponent = \"All\";",
  ].join("\n"),
  "buy filter options"
);

replaceRegex(
  /  if \(els\.buySizeChips\) \{[\s\S]*?\n  \}\n/,
  "",
  "remove size chips"
);

replaceRegex(
  /  if \(els\.buyShipFilters\) \{[\s\S]*?\n  if \(els\.buyShipComponentSelect\) \{[\s\S]*?\n  \}\n/,
  [
    "  const showShipFilters = tab === \"ships\" || tab === \"rentals\";",
    "  if (els.buyShipFilters) {",
    "    els.buyShipFilters.hidden = !showShipFilters;",
    "    els.buyShipFilters.style.display = showShipFilters ? \"\" : \"none\";",
    "  }",
    "  if (els.buyShipSupportFilters) {",
    "    els.buyShipSupportFilters.hidden = !showShipFilters;",
    "    els.buyShipSupportFilters.style.display = showShipFilters ? \"\" : \"none\";",
    "  }",
    "  if (els.buyShipCareerSelect) {",
    "    els.buyShipCareerSelect.innerHTML = shipCareerOptions.map((value) => `<option value=\"${value}\" ${value === state.buyShipCareer ? \"selected\" : \"\"}>${value}</option>`).join(\"\");",
    "    els.buyShipCareerSelect.value = state.buyShipCareer;",
    "  }",
    "  if (els.buyShipRoleSelect) {",
    "    els.buyShipRoleSelect.innerHTML = shipRoles.map((value) => `<option value=\"${value}\" ${value === state.buyShipRole ? \"selected\" : \"\"}>${value}</option>`).join(\"\");",
    "    els.buyShipRoleSelect.value = state.buyShipRole;",
    "  }",
    "  if (els.buyShipSizeSelect) {",
    "    els.buyShipSizeSelect.innerHTML = shipSizes.map((value) => `<option value=\"${value}\" ${value === state.buyShipSize ? \"selected\" : \"\"}>${value}</option>`).join(\"\");",
    "    els.buyShipSizeSelect.value = state.buyShipSize;",
    "  }",
    "  if (els.buyShipWeaponSelect) {",
    "    els.buyShipWeaponSelect.innerHTML = shipWeaponOptions.map((value) => `<option value=\"${value}\" ${value === state.buyShipWeapon ? \"selected\" : \"\"}>${value}</option>`).join(\"\");",
    "    els.buyShipWeaponSelect.value = state.buyShipWeapon;",
    "  }",
    "  if (els.buyShipComponentSelect) {",
    "    els.buyShipComponentSelect.innerHTML = shipComponentOptions.map((value) => `<option value=\"${value}\" ${value === state.buyShipComponent ? \"selected\" : \"\"}>${value}</option>`).join(\"\");",
    "    els.buyShipComponentSelect.value = state.buyShipComponent;",
    "  }",
  ].join("\n"),
  "ship filters render"
);

replaceRegex(
  /const career = tab === "ships" \? type : "";/,
  "const career = tab === \"ships\" || tab === \"rentals\" ? type : \"\";",
  "career line"
);
replaceRegex(
  /const role = tab === "ships" \? subtype : "";/,
  "const role = tab === \"ships\" || tab === \"rentals\" ? subtype : \"\";",
  "role line"
);
replaceRegex(
  /const size = buyEntrySize\(selected, tab\);/,
  "const size = tab === \"ships\" || tab === \"rentals\" ? buyEntrySize(selected, tab) : \"\";",
  "size line"
);

text = text.replace(/offerLabel\(/g, "offerLocationName(");
text = text.replace(/if \(els\.buyShipRoleSelect\)\s*\{\n    els\.buyShipRoleSelect\.innerHTML = shipRoles\.map\(\(value\) => `<option value="\$\{value\}" \$\{value === state\.buyShipRole \? "selected" : ""\}>\$\{value\}<\/option>`\)\.join\(""\);\n    els\.buyShipRoleSelect\.value = state\.buyShipRole;\n  \}\n  if \(els\.buyShipWeaponSelect\)/, `if (els.buyShipCareerSelect) {\n    els.buyShipCareerSelect.innerHTML = shipCareerOptions.map((value) => \`<option value=\"\${value}\" \${value === state.buyShipCareer ? \"selected\" : \"\"}>\${value}</option>\`).join(\"\");\n    els.buyShipCareerSelect.value = state.buyShipCareer;\n  }\n  if (els.buyShipRoleSelect) {\n    els.buyShipRoleSelect.innerHTML = shipRoles.map((value) => \`<option value=\"\${value}\" \${value === state.buyShipRole ? \"selected\" : \"\"}>\${value}</option>\`).join(\"\");\n    els.buyShipRoleSelect.value = state.buyShipRole;\n  }\n  if (els.buyShipSizeSelect) {\n    els.buyShipSizeSelect.innerHTML = shipSizes.map((value) => \`<option value=\"\${value}\" \${value === state.buyShipSize ? \"selected\" : \"\"}>\${value}</option>\`).join(\"\");\n    els.buyShipSizeSelect.value = state.buyShipSize;\n  }\n  if (els.buyShipWeaponSelect)`);\n\nreplaceRegex(\n  /\\n  els\\.buySizeChips\\?\\.addEventListener\\(\"click\", \\(event\\) => \\{[\\s\\S]*?\\n  \\}\\);/,\n  \"\",\n  \"size chip listener\"\n);\nreplaceRegex(\n  /  els\\.buyShipRoleSelect\\?\\.addEventListener\\(\"change\", \\(event\\) => \\{\\n    state\\.buyShipRole = event\\.target\\.value \\|\\| \"All\";\\n    state\\.buySelectedId = \\\"\\\";\\n    renderBuy\\(\\);\\n    saveState\\(\\);\\n  \\}\\);\\n  els\\.buyShipWeaponSelect\\?\\.addEventListener\\(\"change\", \\(event\\) => \\{[\\s\\S]*?\\n  \\}\\);/,\n+  [
    "  els.buyShipCareerSelect?.addEventListener(\"change\", (event) => {",
    "    state.buyShipCareer = event.target.value || \"All\";",
    "    state.buySelectedId = \"\";",
    "    renderBuy();",
    "    saveState();",
    "  });",
    "  els.buyShipRoleSelect?.addEventListener(\"change\", (event) => {",
    "    state.buyShipRole = event.target.value || \"All\";",
    "    state.buySelectedId = \"\";",
    "    renderBuy();",
    "    saveState();",
    "  });",
    "  els.buyShipSizeSelect?.addEventListener(\"change\", (event) => {",
    "    state.buyShipSize = event.target.value || \"All\";",
    "    state.buySelectedId = \"\";",
    "    renderBuy();",
    "    saveState();",
    "  });",
    "  els.buyShipWeaponSelect?.addEventListener(\"change\", (event) => {",
    "    state.buyShipWeapon = event.target.value || \"All\";",
    "    state.buySelectedId = \"\";",
    "    renderBuy();",
    "    saveState();",
    "  });",
    "  els.buyShipComponentSelect?.addEventListener(\"change\", (event) => {",
    "    state.buyShipComponent = event.target.value || \"All\";",
    "    state.buySelectedId = \"\";",
    "    renderBuy();",
    "    saveState();",
    "  });",
  ].join("\n"),
  "ship select listeners"
);

replaceRegex(
  /"buySystemSelect",\n    "buyAreaSelect",\n    "buyLocationSelect",\n    "buyTypeChips",\n    "buySubtypeChips",\n    "buyShipFilters",\n    "buyShipRoleSelect",\n    "buyShipWeaponSelect",\n    "buyShipComponentSelect",\n    "buySizeChips",/,
  [
    "\"buySystemSelect\",",
    "    \"buyAreaSelect\",",
    "    \"buyLocationSelect\",",
    "    \"buyTypeChips\",",
    "    \"buySubtypeChips\",",
    "    \"buyShipFilters\",",
    "    \"buyShipSupportFilters\",",
    "    \"buyShipCareerSelect\",",
    "    \"buyShipRoleSelect\",",
    "    \"buyShipSizeSelect\",",
    "    \"buyShipWeaponSelect\",",
    "    \"buyShipComponentSelect\",",
  ].join("\n"),
  "els list"
);

replaceRegex(
  /buyShipSize: "All",\n  buyShipRole: "All",\n  buyShipWeapon: "All",\n  buyShipComponent: "All",/,
  "buyShipCareer: \"All\",\n  buyShipSize: \"All\",\n  buyShipRole: \"All\",\n  buyShipWeapon: \"All\",\n  buyShipComponent: \"All\",",
  "state defaults"
);
replaceRegex(
  /buyShipSize: parsed\.buyShipSize \|\| "All",\n  buyShipRole: parsed\.buyShipRole \|\| "All",\n  buyShipWeapon: parsed\.buyShipWeapon \|\| "All",\n  buyShipComponent: parsed\.buyShipComponent \|\| "All",/,
  "buyShipCareer: parsed.buyShipCareer || \"All\",\n  buyShipSize: parsed.buyShipSize || \"All\",\n  buyShipRole: parsed.buyShipRole || \"All\",\n  buyShipWeapon: parsed.buyShipWeapon || \"All\",\n  buyShipComponent: parsed.buyShipComponent || \"All\",",
  "load profile"
);
replaceRegex(
  /buyShipSize: state\.buyShipSize,\n      buyShipRole: state\.buyShipRole,\n      buyShipWeapon: state\.buyShipWeapon,\n      buyShipComponent: state\.buyShipComponent,/,
  "buyShipCareer: state.buyShipCareer,\n      buyShipSize: state.buyShipSize,\n      buyShipRole: state.buyShipRole,\n      buyShipWeapon: state.buyShipWeapon,\n      buyShipComponent: state.buyShipComponent,",
  "save profile"
);

replaceRegex(
  /buyShipSize: "All",\n    buyShipRole: "All",\n    buyShipWeapon: "All",\n    buyShipComponent: "All",\n    buySelectedId: "",/,
  "buyShipCareer: \"All\",\n    buyShipSize: \"All\",\n    buyShipRole: \"All\",\n    buyShipWeapon: \"All\",\n    buyShipComponent: \"All\",\n    buySelectedId: \"\",",
  "default profile"
);

replaceRegex(
  /buyShipSize: "All",\n  buyShipRole: "All",\n  buyShipWeapon: "All",\n  buyShipComponent: "All",\n  buySelectedId: "",/,
  "buyShipCareer: \"All\",\n  buyShipSize: \"All\",\n  buyShipRole: \"All\",\n  buyShipWeapon: \"All\",\n  buyShipComponent: \"All\",\n  buySelectedId: \"\",",
  "state block"
);

fs.writeFileSync(path, text, "latin1");
console.log("app.js updated");
